import type { Metadata } from 'next'
import './globals.css'
import { Poppins } from 'next/font/google'
import { Toaster } from 'sonner'

import React from 'react'
import { PageTransition } from '@/components'

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: 'Aspire 4 Hire',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <PageTransition>
          {children} <Toaster richColors />
        </PageTransition>
      </body>
    </html>
  )
}
